# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/cmake/bin/cmake

# The command to remove a file.
RM = /usr/local/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jinzhuguang/code/TSCached

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jinzhuguang/code/TSCached

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/cmake/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/cmake/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jinzhuguang/code/TSCached/CMakeFiles /home/jinzhuguang/code/TSCached/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jinzhuguang/code/TSCached/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TSCached

# Build rule for target.
TSCached: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TSCached
.PHONY : TSCached

# fast build rule for target.
TSCached/fast:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/build
.PHONY : TSCached/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/main.cpp.s
.PHONY : main.cpp.s

manager/ClearTaskManager.o: manager/ClearTaskManager.cpp.o

.PHONY : manager/ClearTaskManager.o

# target to build an object file
manager/ClearTaskManager.cpp.o:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/manager/ClearTaskManager.cpp.o
.PHONY : manager/ClearTaskManager.cpp.o

manager/ClearTaskManager.i: manager/ClearTaskManager.cpp.i

.PHONY : manager/ClearTaskManager.i

# target to preprocess a source file
manager/ClearTaskManager.cpp.i:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/manager/ClearTaskManager.cpp.i
.PHONY : manager/ClearTaskManager.cpp.i

manager/ClearTaskManager.s: manager/ClearTaskManager.cpp.s

.PHONY : manager/ClearTaskManager.s

# target to generate assembly for a file
manager/ClearTaskManager.cpp.s:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/manager/ClearTaskManager.cpp.s
.PHONY : manager/ClearTaskManager.cpp.s

manager/Config.o: manager/Config.cpp.o

.PHONY : manager/Config.o

# target to build an object file
manager/Config.cpp.o:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/manager/Config.cpp.o
.PHONY : manager/Config.cpp.o

manager/Config.i: manager/Config.cpp.i

.PHONY : manager/Config.i

# target to preprocess a source file
manager/Config.cpp.i:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/manager/Config.cpp.i
.PHONY : manager/Config.cpp.i

manager/Config.s: manager/Config.cpp.s

.PHONY : manager/Config.s

# target to generate assembly for a file
manager/Config.cpp.s:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/manager/Config.cpp.s
.PHONY : manager/Config.cpp.s

manager/Timer.o: manager/Timer.cpp.o

.PHONY : manager/Timer.o

# target to build an object file
manager/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/manager/Timer.cpp.o
.PHONY : manager/Timer.cpp.o

manager/Timer.i: manager/Timer.cpp.i

.PHONY : manager/Timer.i

# target to preprocess a source file
manager/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/manager/Timer.cpp.i
.PHONY : manager/Timer.cpp.i

manager/Timer.s: manager/Timer.cpp.s

.PHONY : manager/Timer.s

# target to generate assembly for a file
manager/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/manager/Timer.cpp.s
.PHONY : manager/Timer.cpp.s

manager/TimerManager.o: manager/TimerManager.cpp.o

.PHONY : manager/TimerManager.o

# target to build an object file
manager/TimerManager.cpp.o:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/manager/TimerManager.cpp.o
.PHONY : manager/TimerManager.cpp.o

manager/TimerManager.i: manager/TimerManager.cpp.i

.PHONY : manager/TimerManager.i

# target to preprocess a source file
manager/TimerManager.cpp.i:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/manager/TimerManager.cpp.i
.PHONY : manager/TimerManager.cpp.i

manager/TimerManager.s: manager/TimerManager.cpp.s

.PHONY : manager/TimerManager.s

# target to generate assembly for a file
manager/TimerManager.cpp.s:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/manager/TimerManager.cpp.s
.PHONY : manager/TimerManager.cpp.s

protobuf/point.grpc.pb.o: protobuf/point.grpc.pb.cc.o

.PHONY : protobuf/point.grpc.pb.o

# target to build an object file
protobuf/point.grpc.pb.cc.o:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/protobuf/point.grpc.pb.cc.o
.PHONY : protobuf/point.grpc.pb.cc.o

protobuf/point.grpc.pb.i: protobuf/point.grpc.pb.cc.i

.PHONY : protobuf/point.grpc.pb.i

# target to preprocess a source file
protobuf/point.grpc.pb.cc.i:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/protobuf/point.grpc.pb.cc.i
.PHONY : protobuf/point.grpc.pb.cc.i

protobuf/point.grpc.pb.s: protobuf/point.grpc.pb.cc.s

.PHONY : protobuf/point.grpc.pb.s

# target to generate assembly for a file
protobuf/point.grpc.pb.cc.s:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/protobuf/point.grpc.pb.cc.s
.PHONY : protobuf/point.grpc.pb.cc.s

protobuf/point.pb.o: protobuf/point.pb.cc.o

.PHONY : protobuf/point.pb.o

# target to build an object file
protobuf/point.pb.cc.o:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/protobuf/point.pb.cc.o
.PHONY : protobuf/point.pb.cc.o

protobuf/point.pb.i: protobuf/point.pb.cc.i

.PHONY : protobuf/point.pb.i

# target to preprocess a source file
protobuf/point.pb.cc.i:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/protobuf/point.pb.cc.i
.PHONY : protobuf/point.pb.cc.i

protobuf/point.pb.s: protobuf/point.pb.cc.s

.PHONY : protobuf/point.pb.s

# target to generate assembly for a file
protobuf/point.pb.cc.s:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/protobuf/point.pb.cc.s
.PHONY : protobuf/point.pb.cc.s

server/TSCachedServer.o: server/TSCachedServer.cpp.o

.PHONY : server/TSCachedServer.o

# target to build an object file
server/TSCachedServer.cpp.o:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/server/TSCachedServer.cpp.o
.PHONY : server/TSCachedServer.cpp.o

server/TSCachedServer.i: server/TSCachedServer.cpp.i

.PHONY : server/TSCachedServer.i

# target to preprocess a source file
server/TSCachedServer.cpp.i:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/server/TSCachedServer.cpp.i
.PHONY : server/TSCachedServer.cpp.i

server/TSCachedServer.s: server/TSCachedServer.cpp.s

.PHONY : server/TSCachedServer.s

# target to generate assembly for a file
server/TSCachedServer.cpp.s:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/server/TSCachedServer.cpp.s
.PHONY : server/TSCachedServer.cpp.s

server/TSCachedServiceImpl.o: server/TSCachedServiceImpl.cpp.o

.PHONY : server/TSCachedServiceImpl.o

# target to build an object file
server/TSCachedServiceImpl.cpp.o:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/server/TSCachedServiceImpl.cpp.o
.PHONY : server/TSCachedServiceImpl.cpp.o

server/TSCachedServiceImpl.i: server/TSCachedServiceImpl.cpp.i

.PHONY : server/TSCachedServiceImpl.i

# target to preprocess a source file
server/TSCachedServiceImpl.cpp.i:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/server/TSCachedServiceImpl.cpp.i
.PHONY : server/TSCachedServiceImpl.cpp.i

server/TSCachedServiceImpl.s: server/TSCachedServiceImpl.cpp.s

.PHONY : server/TSCachedServiceImpl.s

# target to generate assembly for a file
server/TSCachedServiceImpl.cpp.s:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/server/TSCachedServiceImpl.cpp.s
.PHONY : server/TSCachedServiceImpl.cpp.s

storage/BlockData.o: storage/BlockData.cpp.o

.PHONY : storage/BlockData.o

# target to build an object file
storage/BlockData.cpp.o:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/storage/BlockData.cpp.o
.PHONY : storage/BlockData.cpp.o

storage/BlockData.i: storage/BlockData.cpp.i

.PHONY : storage/BlockData.i

# target to preprocess a source file
storage/BlockData.cpp.i:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/storage/BlockData.cpp.i
.PHONY : storage/BlockData.cpp.i

storage/BlockData.s: storage/BlockData.cpp.s

.PHONY : storage/BlockData.s

# target to generate assembly for a file
storage/BlockData.cpp.s:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/storage/BlockData.cpp.s
.PHONY : storage/BlockData.cpp.s

storage/TimeSeries.o: storage/TimeSeries.cpp.o

.PHONY : storage/TimeSeries.o

# target to build an object file
storage/TimeSeries.cpp.o:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/storage/TimeSeries.cpp.o
.PHONY : storage/TimeSeries.cpp.o

storage/TimeSeries.i: storage/TimeSeries.cpp.i

.PHONY : storage/TimeSeries.i

# target to preprocess a source file
storage/TimeSeries.cpp.i:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/storage/TimeSeries.cpp.i
.PHONY : storage/TimeSeries.cpp.i

storage/TimeSeries.s: storage/TimeSeries.cpp.s

.PHONY : storage/TimeSeries.s

# target to generate assembly for a file
storage/TimeSeries.cpp.s:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/storage/TimeSeries.cpp.s
.PHONY : storage/TimeSeries.cpp.s

storage/TimeSeriesMap.o: storage/TimeSeriesMap.cpp.o

.PHONY : storage/TimeSeriesMap.o

# target to build an object file
storage/TimeSeriesMap.cpp.o:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/storage/TimeSeriesMap.cpp.o
.PHONY : storage/TimeSeriesMap.cpp.o

storage/TimeSeriesMap.i: storage/TimeSeriesMap.cpp.i

.PHONY : storage/TimeSeriesMap.i

# target to preprocess a source file
storage/TimeSeriesMap.cpp.i:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/storage/TimeSeriesMap.cpp.i
.PHONY : storage/TimeSeriesMap.cpp.i

storage/TimeSeriesMap.s: storage/TimeSeriesMap.cpp.s

.PHONY : storage/TimeSeriesMap.s

# target to generate assembly for a file
storage/TimeSeriesMap.cpp.s:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/storage/TimeSeriesMap.cpp.s
.PHONY : storage/TimeSeriesMap.cpp.s

storage/point.o: storage/point.cpp.o

.PHONY : storage/point.o

# target to build an object file
storage/point.cpp.o:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/storage/point.cpp.o
.PHONY : storage/point.cpp.o

storage/point.i: storage/point.cpp.i

.PHONY : storage/point.i

# target to preprocess a source file
storage/point.cpp.i:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/storage/point.cpp.i
.PHONY : storage/point.cpp.i

storage/point.s: storage/point.cpp.s

.PHONY : storage/point.s

# target to generate assembly for a file
storage/point.cpp.s:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/storage/point.cpp.s
.PHONY : storage/point.cpp.s

utils/PointUtils.o: utils/PointUtils.cpp.o

.PHONY : utils/PointUtils.o

# target to build an object file
utils/PointUtils.cpp.o:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/utils/PointUtils.cpp.o
.PHONY : utils/PointUtils.cpp.o

utils/PointUtils.i: utils/PointUtils.cpp.i

.PHONY : utils/PointUtils.i

# target to preprocess a source file
utils/PointUtils.cpp.i:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/utils/PointUtils.cpp.i
.PHONY : utils/PointUtils.cpp.i

utils/PointUtils.s: utils/PointUtils.cpp.s

.PHONY : utils/PointUtils.s

# target to generate assembly for a file
utils/PointUtils.cpp.s:
	$(MAKE) -f CMakeFiles/TSCached.dir/build.make CMakeFiles/TSCached.dir/utils/PointUtils.cpp.s
.PHONY : utils/PointUtils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TSCached"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... manager/ClearTaskManager.o"
	@echo "... manager/ClearTaskManager.i"
	@echo "... manager/ClearTaskManager.s"
	@echo "... manager/Config.o"
	@echo "... manager/Config.i"
	@echo "... manager/Config.s"
	@echo "... manager/Timer.o"
	@echo "... manager/Timer.i"
	@echo "... manager/Timer.s"
	@echo "... manager/TimerManager.o"
	@echo "... manager/TimerManager.i"
	@echo "... manager/TimerManager.s"
	@echo "... protobuf/point.grpc.pb.o"
	@echo "... protobuf/point.grpc.pb.i"
	@echo "... protobuf/point.grpc.pb.s"
	@echo "... protobuf/point.pb.o"
	@echo "... protobuf/point.pb.i"
	@echo "... protobuf/point.pb.s"
	@echo "... server/TSCachedServer.o"
	@echo "... server/TSCachedServer.i"
	@echo "... server/TSCachedServer.s"
	@echo "... server/TSCachedServiceImpl.o"
	@echo "... server/TSCachedServiceImpl.i"
	@echo "... server/TSCachedServiceImpl.s"
	@echo "... storage/BlockData.o"
	@echo "... storage/BlockData.i"
	@echo "... storage/BlockData.s"
	@echo "... storage/TimeSeries.o"
	@echo "... storage/TimeSeries.i"
	@echo "... storage/TimeSeries.s"
	@echo "... storage/TimeSeriesMap.o"
	@echo "... storage/TimeSeriesMap.i"
	@echo "... storage/TimeSeriesMap.s"
	@echo "... storage/point.o"
	@echo "... storage/point.i"
	@echo "... storage/point.s"
	@echo "... utils/PointUtils.o"
	@echo "... utils/PointUtils.i"
	@echo "... utils/PointUtils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

