// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: point.proto
#ifndef GRPC_point_2eproto__INCLUDED
#define GRPC_point_2eproto__INCLUDED

#include "point.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace TSCached {

class TSCachedService final {
 public:
  static constexpr char const* service_full_name() {
    return "TSCached.TSCachedService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status QueryPoints(::grpc::ClientContext* context, const ::TSCached::QueryRequest& request, ::TSCached::QueryResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TSCached::QueryResponse>> AsyncQueryPoints(::grpc::ClientContext* context, const ::TSCached::QueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TSCached::QueryResponse>>(AsyncQueryPointsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TSCached::QueryResponse>> PrepareAsyncQueryPoints(::grpc::ClientContext* context, const ::TSCached::QueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TSCached::QueryResponse>>(PrepareAsyncQueryPointsRaw(context, request, cq));
    }
    virtual ::grpc::Status WritePoints(::grpc::ClientContext* context, const ::TSCached::WriteRequest& request, ::TSCached::WriteResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TSCached::WriteResponse>> AsyncWritePoints(::grpc::ClientContext* context, const ::TSCached::WriteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TSCached::WriteResponse>>(AsyncWritePointsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TSCached::WriteResponse>> PrepareAsyncWritePoints(::grpc::ClientContext* context, const ::TSCached::WriteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TSCached::WriteResponse>>(PrepareAsyncWritePointsRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void QueryPoints(::grpc::ClientContext* context, const ::TSCached::QueryRequest* request, ::TSCached::QueryResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void QueryPoints(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TSCached::QueryResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void QueryPoints(::grpc::ClientContext* context, const ::TSCached::QueryRequest* request, ::TSCached::QueryResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void QueryPoints(::grpc::ClientContext* context, const ::TSCached::QueryRequest* request, ::TSCached::QueryResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void QueryPoints(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TSCached::QueryResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void QueryPoints(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TSCached::QueryResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void WritePoints(::grpc::ClientContext* context, const ::TSCached::WriteRequest* request, ::TSCached::WriteResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void WritePoints(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TSCached::WriteResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void WritePoints(::grpc::ClientContext* context, const ::TSCached::WriteRequest* request, ::TSCached::WriteResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void WritePoints(::grpc::ClientContext* context, const ::TSCached::WriteRequest* request, ::TSCached::WriteResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void WritePoints(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TSCached::WriteResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void WritePoints(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TSCached::WriteResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TSCached::QueryResponse>* AsyncQueryPointsRaw(::grpc::ClientContext* context, const ::TSCached::QueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TSCached::QueryResponse>* PrepareAsyncQueryPointsRaw(::grpc::ClientContext* context, const ::TSCached::QueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TSCached::WriteResponse>* AsyncWritePointsRaw(::grpc::ClientContext* context, const ::TSCached::WriteRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TSCached::WriteResponse>* PrepareAsyncWritePointsRaw(::grpc::ClientContext* context, const ::TSCached::WriteRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status QueryPoints(::grpc::ClientContext* context, const ::TSCached::QueryRequest& request, ::TSCached::QueryResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TSCached::QueryResponse>> AsyncQueryPoints(::grpc::ClientContext* context, const ::TSCached::QueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TSCached::QueryResponse>>(AsyncQueryPointsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TSCached::QueryResponse>> PrepareAsyncQueryPoints(::grpc::ClientContext* context, const ::TSCached::QueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TSCached::QueryResponse>>(PrepareAsyncQueryPointsRaw(context, request, cq));
    }
    ::grpc::Status WritePoints(::grpc::ClientContext* context, const ::TSCached::WriteRequest& request, ::TSCached::WriteResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TSCached::WriteResponse>> AsyncWritePoints(::grpc::ClientContext* context, const ::TSCached::WriteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TSCached::WriteResponse>>(AsyncWritePointsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TSCached::WriteResponse>> PrepareAsyncWritePoints(::grpc::ClientContext* context, const ::TSCached::WriteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TSCached::WriteResponse>>(PrepareAsyncWritePointsRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void QueryPoints(::grpc::ClientContext* context, const ::TSCached::QueryRequest* request, ::TSCached::QueryResponse* response, std::function<void(::grpc::Status)>) override;
      void QueryPoints(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TSCached::QueryResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void QueryPoints(::grpc::ClientContext* context, const ::TSCached::QueryRequest* request, ::TSCached::QueryResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void QueryPoints(::grpc::ClientContext* context, const ::TSCached::QueryRequest* request, ::TSCached::QueryResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void QueryPoints(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TSCached::QueryResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void QueryPoints(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TSCached::QueryResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void WritePoints(::grpc::ClientContext* context, const ::TSCached::WriteRequest* request, ::TSCached::WriteResponse* response, std::function<void(::grpc::Status)>) override;
      void WritePoints(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TSCached::WriteResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void WritePoints(::grpc::ClientContext* context, const ::TSCached::WriteRequest* request, ::TSCached::WriteResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void WritePoints(::grpc::ClientContext* context, const ::TSCached::WriteRequest* request, ::TSCached::WriteResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void WritePoints(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TSCached::WriteResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void WritePoints(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::TSCached::WriteResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::TSCached::QueryResponse>* AsyncQueryPointsRaw(::grpc::ClientContext* context, const ::TSCached::QueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::TSCached::QueryResponse>* PrepareAsyncQueryPointsRaw(::grpc::ClientContext* context, const ::TSCached::QueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::TSCached::WriteResponse>* AsyncWritePointsRaw(::grpc::ClientContext* context, const ::TSCached::WriteRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::TSCached::WriteResponse>* PrepareAsyncWritePointsRaw(::grpc::ClientContext* context, const ::TSCached::WriteRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_QueryPoints_;
    const ::grpc::internal::RpcMethod rpcmethod_WritePoints_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status QueryPoints(::grpc::ServerContext* context, const ::TSCached::QueryRequest* request, ::TSCached::QueryResponse* response);
    virtual ::grpc::Status WritePoints(::grpc::ServerContext* context, const ::TSCached::WriteRequest* request, ::TSCached::WriteResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_QueryPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_QueryPoints() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_QueryPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryPoints(::grpc::ServerContext* /*context*/, const ::TSCached::QueryRequest* /*request*/, ::TSCached::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQueryPoints(::grpc::ServerContext* context, ::TSCached::QueryRequest* request, ::grpc::ServerAsyncResponseWriter< ::TSCached::QueryResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_WritePoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_WritePoints() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_WritePoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WritePoints(::grpc::ServerContext* /*context*/, const ::TSCached::WriteRequest* /*request*/, ::TSCached::WriteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWritePoints(::grpc::ServerContext* context, ::TSCached::WriteRequest* request, ::grpc::ServerAsyncResponseWriter< ::TSCached::WriteResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_QueryPoints<WithAsyncMethod_WritePoints<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_QueryPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_QueryPoints() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::TSCached::QueryRequest, ::TSCached::QueryResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::TSCached::QueryRequest* request, ::TSCached::QueryResponse* response) { return this->QueryPoints(context, request, response); }));}
    void SetMessageAllocatorFor_QueryPoints(
        ::grpc::experimental::MessageAllocator< ::TSCached::QueryRequest, ::TSCached::QueryResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::TSCached::QueryRequest, ::TSCached::QueryResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_QueryPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryPoints(::grpc::ServerContext* /*context*/, const ::TSCached::QueryRequest* /*request*/, ::TSCached::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* QueryPoints(
      ::grpc::CallbackServerContext* /*context*/, const ::TSCached::QueryRequest* /*request*/, ::TSCached::QueryResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* QueryPoints(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::TSCached::QueryRequest* /*request*/, ::TSCached::QueryResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_WritePoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_WritePoints() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::TSCached::WriteRequest, ::TSCached::WriteResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::TSCached::WriteRequest* request, ::TSCached::WriteResponse* response) { return this->WritePoints(context, request, response); }));}
    void SetMessageAllocatorFor_WritePoints(
        ::grpc::experimental::MessageAllocator< ::TSCached::WriteRequest, ::TSCached::WriteResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::TSCached::WriteRequest, ::TSCached::WriteResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_WritePoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WritePoints(::grpc::ServerContext* /*context*/, const ::TSCached::WriteRequest* /*request*/, ::TSCached::WriteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* WritePoints(
      ::grpc::CallbackServerContext* /*context*/, const ::TSCached::WriteRequest* /*request*/, ::TSCached::WriteResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* WritePoints(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::TSCached::WriteRequest* /*request*/, ::TSCached::WriteResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_QueryPoints<ExperimentalWithCallbackMethod_WritePoints<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_QueryPoints<ExperimentalWithCallbackMethod_WritePoints<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_QueryPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_QueryPoints() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_QueryPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryPoints(::grpc::ServerContext* /*context*/, const ::TSCached::QueryRequest* /*request*/, ::TSCached::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_WritePoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_WritePoints() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_WritePoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WritePoints(::grpc::ServerContext* /*context*/, const ::TSCached::WriteRequest* /*request*/, ::TSCached::WriteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_QueryPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_QueryPoints() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_QueryPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryPoints(::grpc::ServerContext* /*context*/, const ::TSCached::QueryRequest* /*request*/, ::TSCached::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQueryPoints(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_WritePoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_WritePoints() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_WritePoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WritePoints(::grpc::ServerContext* /*context*/, const ::TSCached::WriteRequest* /*request*/, ::TSCached::WriteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWritePoints(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_QueryPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_QueryPoints() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->QueryPoints(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_QueryPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryPoints(::grpc::ServerContext* /*context*/, const ::TSCached::QueryRequest* /*request*/, ::TSCached::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* QueryPoints(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* QueryPoints(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_WritePoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_WritePoints() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->WritePoints(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_WritePoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WritePoints(::grpc::ServerContext* /*context*/, const ::TSCached::WriteRequest* /*request*/, ::TSCached::WriteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* WritePoints(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* WritePoints(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_QueryPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_QueryPoints() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::TSCached::QueryRequest, ::TSCached::QueryResponse>(std::bind(&WithStreamedUnaryMethod_QueryPoints<BaseClass>::StreamedQueryPoints, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_QueryPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status QueryPoints(::grpc::ServerContext* /*context*/, const ::TSCached::QueryRequest* /*request*/, ::TSCached::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedQueryPoints(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::TSCached::QueryRequest,::TSCached::QueryResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_WritePoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_WritePoints() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::TSCached::WriteRequest, ::TSCached::WriteResponse>(std::bind(&WithStreamedUnaryMethod_WritePoints<BaseClass>::StreamedWritePoints, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_WritePoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status WritePoints(::grpc::ServerContext* /*context*/, const ::TSCached::WriteRequest* /*request*/, ::TSCached::WriteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedWritePoints(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::TSCached::WriteRequest,::TSCached::WriteResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_QueryPoints<WithStreamedUnaryMethod_WritePoints<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_QueryPoints<WithStreamedUnaryMethod_WritePoints<Service > > StreamedService;
};

}  // namespace TSCached


#endif  // GRPC_point_2eproto__INCLUDED
